
name: Build

on:
  push:
    branches: [main]

jobs:
  build_ostree_ext_cli:
    runs-on: ubuntu-latest
    # needs to run in the most recent version of Ubuntu to ensure that the ostree version is new enough
    container: ubuntu:rolling

    steps:

    - run: apt-get update && apt-get install -y libssl-dev ostree libostree-1-1 libostree-dev git curl build-essential
    - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    - uses: actions/checkout@v2
      with:
        repository: 'ostreedev/ostree-rs-ext'
        path: 'ostree-rs-ext'
      
    - name: Cache
      id: cache-ostree-rs-ext-target
      uses: actions/cache@v3
      with:
        path: ostree-rs-ext/target/
        key: ${{ runner.os }}-ostree-rs-ext-target

    - run: $HOME/.cargo/bin/cargo build --release
      working-directory: ostree-rs-ext
    - run: ls ostree-rs-ext/target/release
    # upload the binary as an artifact
    - uses: actions/upload-artifact@v2
      with:
        name: ostree-ext-cli
        path: ostree-rs-ext/target/release/ostree-ext-cli

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      TMPROOT: /mnt/tmproot

    steps:
        # - name: Maximize build space
        #   uses: easimon/maximize-build-space@master
        #   with:
        #     root-reserve-mb: 512
        #     swap-size-mb: 1024
        #     remove-dotnet: 'true'
        #     remove-codeql: 'true'
        #     remove-android: 'true'
        #     remove-haskell: 'true'
        #     remove-docker-images: 'true'
          
        - name: Checkout code
          uses: actions/checkout@v2

        - uses: actions/download-artifact@v2
          with:
            name: ostree-ext-cli
            path: ostree-ext-cli

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set script permissions
          run: chmod +x ./scripts/*.sh

        - name: Set script permissions
          run: chmod +x ./scripts/*.sh

        - name: Install dependencies
          run: ./scripts/install_dependencies.sh

        - name: Prepare OSTree
          run: ./scripts/prepare_ostree.sh

        - name: Install packages to build repo
          run: ./scripts/install_packages.sh

        - name: Turn OSTree commit into OCI image
          run: ostree-ext-cli container encapsulate --repo=$TMPROOT/build-repo stable-os/$(uname -m)/standard docker://ghcr.io/${{ github.repository_owner }}/stable-os-build:latest

        - name: Upload filesystem image
          uses: actions/upload-artifact@v2
          with:
            name: filesystem
            path: stable-os-build.tar.gz

        - name: Push Docker image
          run: docker push ghcr.io/${{ github.repository_owner }}/stable-os-build:latest